eureka:
  client:
    serviceUrl.defaultZone: 'http://localhost:8761/eureka/'

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8080/auth/realms/shop-realm'
  zipkin.enabled: false
  boot.admin.client.url: 'http://localhost:5050'
